### ISSUE TITLE
Use of cases.Titler is not multi-go routine safe

### ISSUE THREAD

**Issue by pquerna** [ConductorOne/baton-splunk#5]
```
var titleCaser = cases.Title(language.English)
```
https://github.com/ConductorOne/baton-splunk/blob/2d60a52b10c62a552f8b4cd1ee2e53ba43f45d9c/pkg/connector/helpers.go#L16

Unfortunately, `titleCaser` is not safe to be used as a package level variable, without a lock. Inside  `vendor/golang.org/x/text/transform/transform.go` you can see the `.Reset()` method is called -- because the instance has a local buffer:

```
func String(t Transformer, s string) (result string, n int, err error) {
	t.Reset()
```

This could cause "corrupted" Names in a multi-gorotine/production environment.

**Comment by martinalbert** [comment]
@pquerna I opened PR that moves the creation of `Caser` instance into function that returns the formatted string right away. Let me know if that's ok.
